### PR TITLE
feat: SVG support implemented. reduced bundled size to only ~130KB.

### PR DESCRIPTION
**Pull request by iamriajul**
cleanup: unnecessary png files & bash scripts.
example: windows platform added.

### CODE REVIEW

**Comment by cedvdb** [comment]
Nice work, so this is a gain of about 700 kb ?

**Comment by iamriajul** [comment]
Thanks, when do we expect a new version gets released?

**Comment by cedvdb** [comment]
It is now published

**Comment by cedvdb** [comment]
Have you put any thought on using another svg renderer ? EG: https://pub.dev/packages/jovial_svg  seems to have better performances

**Comment by iamriajul** [comment]
I've been recently researching (in-house research) Fontello, SVG Icons converted to TTF Font, which is very efficient. Font with Icon Widget with IconData is very robust. 

Here is an example of such a font: https://fonts.google.com/noto/specimen/Noto+Color+Emoji?coloronly=true

I'll let you know if those country flags also can be converted into a TTF Font.

**Comment by iamriajul** [comment]
Another example of converting SVG to TTF & Dart files is here: https://github.com/pedrolemoz/unicons-flutter

And also I've been successful in converting our in-house app's SVG icons to TTF and using them in that app.

**Comment by iamriajul** [comment]
I tried those, but they do not support color fonts, I've searched a little on the JS ecosystem to find out any package that will help us generate color fonts, but it seems it is not feasible yet. https://github.com/nfroidure/svgicons2svgfont/issues/163

**Pull request merged**
