### PR TITLE
Restore bundled assets

### PR DESCRIPTION
**Pull request by xvrh**
As discussed in https://github.com/cedvdb/phone_form_field/issues/181 this PR reverts the latest change with network images and go back to bundled assets

### CODE REVIEW

**Comment by xvrh** [comment]
ok, but what is wrong with flutter_svg?

It is very popular and maintained by some members of the Flutter team itself. They have done incredible work on the performance side thanks to their knowledge of the internal of the Flutter engine.

**Comment by cedvdb** [comment]
I know that who maintains the package and I understand that it can be an annoyance for some as they might already have it as a dependency.

Jovial svg reduces the file size but not by much. The rendering is more performant though, which is what I'm after, ie: trying to remove the flashes on the web platform when scrolling.

I'll try to get the same result with flutter_svg.

**Comment by xvrh** [comment]
flutter_svg has an optimized binary format, maybe it results in better performance on the web.
You can try it here on my branch: https://github.com/xvrh/flutter_circle_flags/commit/511fb46a2f934099a2312b25f6116dea7d8b8d6e

**Comment by cedvdb** [comment]
Glad to hear that.

I managed to fix the first load issue by adding a preload method, this is **much** smoother. Feel free to add the svg optimization afterward here.

**Comment by cedvdb** [comment]
@xvrh Could you make a PR with that format ? It actually solves the issue better!

If you could add two words in the readme for future contributors to regenerate those it would be great. Thanks a lot.

**Pull request merged**
