### PR TITLE
Fix for web html renderer

### PR DESCRIPTION
**Pull request by blopker**
After some experimentation, I saw that the images weren't working even before the flutter_svg 2 update. It turns out some SVGs had a circle mask on them, even though the Flutter code also applied a mask. I've removed the SVG mask and now the images show up in the example project using the HTML renderer (`flutter run -d chrome --web-renderer html`). Also tested on canvaskit web and Android.

### CODE REVIEW

**Comment by cedvdb** [comment]
Great find, thanks !

**Comment by blopker** [comment]
@cedvdb, nudge for a release :)

**Comment by cedvdb** [comment]
available on version 1.0.4, I fixed the other bug with the parser and will release another version of the phone form field soon

**Comment by blopker** [comment]
Awesome! Thank you :)

**Comment by blopker** [comment]
Hey! It's been a while, but I would have probably used VSCode's bulk find and replace feature for this. I don't specifically mention using a script in the original comment, so that's my guess. I'll let you know if I find a script though.

**Pull request merged**
