### PR TITLE
Use optimized vector format

### PR DESCRIPTION
**Pull request by xvrh**

### CODE REVIEW

**Comment by cedvdb** [comment]
I'm reverting this as there didn't seem that there was any benefit (on the web) when images are preloaded.

If you require this or want to compare [here is the compiled svg branch ](https://github.com/cedvdb/flutter_circle_flags/tree/flutter_svg_preloading_2)  and [here is the normal one](https://github.com/cedvdb/flutter_circle_flags/tree/flutter_svg_preloading_3)

Both using a preloading mechanism. I did not find any difference (manual testing) so I'll merge the one that does not use precompiled picture.

**Comment by xvrh** [comment]
I'm fine with a revert.

**Comment by cedvdb** [comment]
Do you recall how were those images generated ? Looking at them right now I see those are square images while the original are circles.

**Comment by xvrh** [comment]
@cedvdb The optimised .vec files are generated by running `dart tool/compile_svgs.dart`.

> I see those are square images while the original are circles.

What do you mean exactly? I see the .svg are square. And they both (.svg & .vec) render as circle because of the `ClipOval` widget.

**Comment by cedvdb** [comment]
> What do you mean exactly? 

The [repository](https://github.com/HatScripts/circle-flags/tree/gh-pages/flags) from which the svg are taken has circle flags. I was wondering if the fact that svgs are now squared flags is due to the optimization process that somehow shows information that was hidden or if you changed those files yourself.

image

**Comment by xvrh** [comment]
> tool wasn't part of main for some reason and it's been a long time.

I think actually this PR was reverted entirely.

> The repository from which the svg are taken has circle flags

I think the flags turned square with this previous PR: https://github.com/cedvdb/flutter_circle_flags/pull/11

**Pull request merged**
