### PR TITLE
Generator for flags.dart, updated

### PR DESCRIPTION
**Pull request by Alexqwesa**

### CODE REVIEW

**Comment by Alexqwesa** [comment]
pushed to wrong branch and make new pull request by mistake

**Comment by cedvdb** [comment]
Is it normal that the builder is in the src folder ? I'm used to using build

**Comment by Alexqwesa** [comment]
> Is it normal that the builder is in the src folder ? I'm used to using build

paths in build.yaml  use `lib` dir as root directory, if you want to use path outside of `lib` you need to use subpackage... afaik (but maybe i wrong - didn't test other variants....)

**Comment by cedvdb** [comment]
Yes using a subpackage would be a better solution

**Pull request closed without merging**
